### ISSUE TITLE
Not an issue, Thank you very much!

### ISSUE THREAD

**Issue by huseinzol05** [Wikidepia/indonesian_datasets#1]

**Comment by huseinzol05** [comment]
And, can you share your script how do translate https://github.com/Wikidepia/indonesian_datasets/tree/master/question-answering/squad from EN to ID using https://github.com/ccasimiro88/TranslateAlignRetrieve, thanks!

**Comment by Wikidepia** [comment]
Hi, Thanks! I'm inspired from your malay-dataset repository :D 

I forget how exactly to do it 😅, i think i use [this](https://github.com/ccasimiro88/TranslateAlignRetrieve/blob/multilingual/src/tar/src/retrieve/translate_squad.py) and fill the argument accordingly

**Comment by huseinzol05** [comment]
Done created for Malay, will update the link later!

**Comment by huseinzol05** [comment]
https://github.com/huseinzol05/Malay-Dataset/tree/master/question-answer/squad

**Comment by Wikidepia** [comment]
> https://github.com/huseinzol05/Malay-Dataset/tree/master/question-answer/squad

Awesome 👍
