### ISSUE TITLE
How is unsupervised speech compiled?

### ISSUE THREAD

**Issue by xiaobobo-bilibili** [Wikidepia/indonesian_datasets#4]
By unsupervised I mean [this one](https://github.com/Wikidepia/indonesian_datasets/tree/master/speech/unsupervised) . Can you tell me where did you find these audios and corresponding transcripts?

**Comment by Wikidepia** [comment]
Most of it comes from anchor.fm and Indonesian TV YouTube Channel. I use ASR to create all of the transcripts.

**Comment by xiaobobo-bilibili** [comment]
> anchor.fm

And may I ask which ASR engine did you use? Is that like third-party online service (Azure, Google Cloud, AWS) or an engine you built? (I'm just curious and trying to evaluate the confidence of your amazing data, not interested in the legal side of issues)

**Comment by xiaobobo-bilibili** [comment]
Also, how is the segmentation conducted? Did you use a custom VAD module or did you conduct the segmentation using timestamps in subtitle?
