### ISSUE TITLE
Which ASR engine did unsupervised data use?

### ISSUE THREAD

**Issue by xiaobobo-bilibili** [Wikidepia/indonesian_datasets#5]
By unsupervised I mean [this one](https://github.com/Wikidepia/indonesian_datasets/tree/master/speech/unsupervised) . And may I ask which ASR engine did you use? Is that like third-party online service (Azure, Google Cloud, AWS) or an engine you built? (I'm just curious and trying to evaluate the confidence of your amazing data, not trying to get into the legal side of issues)

**Comment by xiaobobo-bilibili** [comment]
Also, how is the segmentation conducted? Did you use a custom VAD module or did you conduct the segmentation using timestamps in subtitle?

**Comment by Wikidepia** [comment]
Hi, sorry for the late reply, I cant say which ASR engine. Sorry 🙏

For segmentation I use [silero-vad](https://github.com/snakers4/silero-vad).
